### ISSUE TITLE
additional type params break th generation

### ISSUE THREAD

**Issue by AlistairB** [fused-effects/fused-effects-th#2]
https://github.com/fused-effects/fused-effects-th/issues/1 fixed my 'simple' effects and that works yay. However, I also have effects that are parameterized by some additional type.

This could simply be out of scope. I guess there will need to be a line drawn of how complex of an effect is supported. I haven't tried it, but it seems polysemy `makeSem` can handle this based on the example, so perhaps it is feasible. https://hackage.haskell.org/package/polysemy-1.3.0.0/docs/Polysemy.html#v:makeSem_

https://github.com/AlistairB/fused-simple-repro/pull/3 will reproduce the problem.

```haskell
data AppEventEmit (e :: Type) (m :: Type -> Type) k where
  EmitAppEvent :: e -> AppEventEmit e m ()

-- emitAppEvent :: Has (AppEventEmit e) sig m => e -> m ()
-- emitAppEvent = send . EmitAppEvent

makeSmartConstructors ''AppEventEmit
```

With `stack build --ghc-options=-ddump-splices` gives me:

```
/home/blah/dev/fused-simple-repro/src/AppEventEmit.hs:22:1-36: Splicing declarations
    makeSmartConstructors ''AppEventEmit
  ======>

    emitAppEvent ::
/home/blah/dev/fused-simple-repro/src/AppEventEmit.hs:22:1: error:
      forall (e_a1yI :: Type) (m_a1yJ :: Type -> Type) sig.
    The exact Name ‘e_a1yL’ is not in scope
      Has (AppEventEmit e_a1yI) sig m_a1yJ => e_a1yL -> m_a1yJ ()
      Probable cause: you used a unique Template Haskell name (NameU), 
    emitAppEvent a = send (EmitAppEvent a)
      perhaps via newName, but did not bind it
    {-# INLINABLE emitAppEvent #-}
      If that's it, then -ddump-splices might be useful
   |
22 | makeSmartConstructors ''AppEventEmit
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


--  While building package fused-simple-repro-0.1.0.0 using:
      /home/blah/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:fused-simple-repro exe:fused-simple-repro-exe --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by patrickt** [comment]
Aha, that’s the same bug cropping up in another place—it’s those type annotations. Will fix! Thank you so much for your patience.

**Comment by patrickt** [comment]
Oof, it’s been like two weeks since I wrote this code and already I forget how most of it works.

**Comment by AlistairB** [comment]
Haha, the joys of template haskell ;)

**Comment by patrickt** [comment]
This should be fixed on `master` now. @AlistairB, can you verify?

**Comment by AlistairB** [comment]
@patrickt Thanks! This works! I now am using this to generate the send functions for all my effects but one.

The case that is now failing is when there are typeclass constraints on the effect data constructor.

```haskell
data WriteJson (m :: Type -> Type) k where
  WriteJson :: ToJSON a => a -> WriteJson m ()

-- writeJson :: (Has WriteJson sig m, ToJSON a) => a -> m ()
-- writeJson = send . WriteJson

makeSmartConstructors ''WriteJson
```

produces:

```
/home/blah/dev/fused-simple-repro/src/WriteJson.hs:23:1: error:
    • Expected kind ‘* -> *’, but ‘a_X9xz’ has kind ‘*’
    • In the first argument of ‘WriteJson’, namely ‘a_X9xz’
      In the first argument of ‘Has’, namely ‘(WriteJson a_X9xz)’
      In the type signature:
        writeJson :: forall (a_X9xz :: Type) (m_a9xz :: Type -> Type) sig.
                     Has (WriteJson a_X9xz) sig m_a9xz => a_X9xz -> m_a9xz ()
   |
23 | makeSmartConstructors ''WriteJson
   |
```

I updated https://github.com/AlistairB/fused-simple-repro/pull/3 with this new case. See https://github.com/AlistairB/fused-simple-repro/blob/c503b474eef4a6d358a3de5838aa6021729986a7/src/WriteJson.hs

**Comment by patrickt** [comment]
@AlistairB Aha, perfect. I’ll fix this one too. Thank you so much for being my guinea pig here.

**Comment by patrickt** [comment]
@AlistairB Does this work for you (off of `master`?)

**Comment by AlistairB** [comment]
Yup all working now. Thanks!
